/**
 ******************************************************************************
 * File Name          : flags.h
 * Date               : 23.12.2019.
 * Description        : Program Flags Header
 ******************************************************************************
 *
 *
 ******************************************************************************
 */
 
#ifndef __FLAGS_H__
#define __FLAGS_H__                           FW_BUILD // version
/* Includes ------------------------------------------------------------------*/
#include "stm32f7xx.h"
/* Exported Define -----------------------------------------------------------*/
/* Exported types ------------------------------------------------------------*/
/* Exported variables  -------------------------------------------------------*/
extern __IO uint32_t sysfl, sysfl1, sysfl2, sysfl3;
/* Exported Macro   --------------------------------------------------------- */
/***********************************************************************
**	 	F L A G S 		1      R E G I S T E R      
***********************************************************************/
#define SYS_NewLogSet()                 (sysfl |=  (0x1U<<0))
#define SYS_NewLogReset()               (sysfl &=(~(0x1U<<0)))
#define IsSYS_NewLogSet()               (sysfl &   (0x1U<<0))
#define SYS_LogListFullSet()            (sysfl |=  (0x1U<<1))
#define SYS_LogListFullReset()          (sysfl &=(~(0x1U<<1)))
#define IsSYS_LogListFullSet()          (sysfl &   (0x1U<<1))
#define SYS_FileRxOkSet()               (sysfl |=  (0x1U<<2))
#define SYS_FileRxOkReset()             (sysfl &=(~(0x1U<<2)))
#define IsSYS_FileRxOkSet()             (sysfl &   (0x1U<<2))
#define SYS_FileRxFailSet()             (sysfl |=  (0x1U<<3))
#define SYS_FileRxFailReset()           (sysfl &=(~(0x1U<<3)))
#define IsSYS_FileRxFailSet()           (sysfl &   (0x1U<<3))
#define SYS_UpdOkSet()                  (sysfl |=  (0x1U<<4))
#define SYS_UpdOkReset()                (sysfl &=(~(0x1U<<4)))
#define IsSYS_UpdOkSet()                (sysfl &   (0x1U<<4))
#define SYS_UpdFailSet()                (sysfl |=  (0x1U<<5))
#define SYS_UpdFailReset()              (sysfl &=(~(0x1U<<5)))
#define IsSYS_UpdFailSet()              (sysfl &   (0x1U<<5))
#define SYS_ImageRqSet()                (sysfl |=  (0x1U<<6))
#define SYS_ImageRqReset()              (sysfl &=(~(0x1U<<6)))
#define IsSYS_ImageRqSet()              (sysfl &   (0x1U<<6))
#define SYS_FwRqSet()                   (sysfl |=  (0x1U<<7))
#define SYS_FwRqReset()                 (sysfl &=(~(0x1U<<7)))
#define IsSYS_FwRqSet()                 (sysfl &   (0x1U<<7))
#define StartUpdate()                   (sysfl |=  (0x1U<<8))
#define StopUpdate()                    (sysfl &=(~(0x1U<<8)))
#define IsUpdateActiv()                 (sysfl &   (0x1U<<8))
#define RS485_StartUpdate()             (sysfl |=  (0x1U<<9))
#define RS485_StopUpdate()              (sysfl &=(~(0x1U<<9)))
#define IsRS485_UpdateActiv()           (sysfl &   (0x1U<<9))
#define RS485_ResponseSet()             (sysfl |=  (0x1U<<10))
#define RS485_ResponseReset()           (sysfl &=(~(0x1U<<10)))
#define IsRS485_ResponseRdy()           (sysfl &   (0x1U<<10))
#define ButtonRemoteSet()               (sysfl |=  (0x1U<<11))
#define ButtonRemoteReset()             (sysfl &=(~(0x1U<<11)))
#define IsButtonRemoteActiv()           (sysfl &   (0x1U<<11))
#define ButtonOpenSet()                 (sysfl |=  (0x1U<<12)) 
#define ButtonOpenReset()               (sysfl &=(~(0x1U<<12)))
#define IsButtonOpenActiv()             (sysfl &   (0x1U<<12))
#define ButtonOkSet()                   (sysfl |=  (0x1U<<13)) 
#define ButtonOkReset()                 (sysfl &=(~(0x1U<<13)))
#define IsButtonOkActiv()               (sysfl &   (0x1U<<13))
#define ButtonUpdateSet()               (sysfl |=  (0x1U<<14)) 
#define ButtonUpdateReset()             (sysfl &=(~(0x1U<<14)))
#define IsButtonUpdateActiv()           (sysfl &   (0x1U<<14))
#define SetpointUpdateSet()             (sysfl |=  (0x1U<<15)) 
#define SetpointUpdateReset()           (sysfl &=(~(0x1U<<15)))
#define IsSetpointUpdateActiv()         (sysfl &   (0x1U<<15))
#define RoomTempUpdateSet()             (sysfl |=  (0x1U<<16)) 
#define RoomTempUpdateReset()           (sysfl &=(~(0x1U<<16)))
#define IsRoomTempUpdateActiv()         (sysfl &   (0x1U<<16))
#define NtcUpdateSet()                  (sysfl |=  (0x1U<<17)) 
#define NtcUpdateReset()                (sysfl &=(~(0x1U<<17)))
#define IsNtcUpdateActiv()              (sysfl &   (0x1U<<17))
#define NtcValidSet()                   (sysfl |=  (0x1U<<18))
#define NtcValidReset()                 (sysfl &=(~(0x1U<<18)))
#define IsNtcValidActiv()               (sysfl &   (0x1U<<18))
#define RtcValidSet()                   (sysfl |=  (0x1U<<19))
#define RtcValidReset()                 (sysfl &=(~(0x1U<<19)))
#define IsRtcValidActiv()               (sysfl &   (0x1U<<19))
#define WFC_UpdateSet()                 (sysfl |=  (0x1U<<20))
#define WFC_UpdateReset()               (sysfl &=(~(0x1U<<20)))
#define IsWFC_UpdateActiv()             (sysfl &   (0x1U<<20))
#define WFC_ValidSet()                  (sysfl |=  (0x1U<<21))
#define WFC_ValidReset()                (sysfl &=(~(0x1U<<21)))
#define IsWFC_ValidActiv()              (sysfl &   (0x1U<<21))
#define ScrnsvrEnable()                 (sysfl |=  (0x1U<<22)) 
#define ScrnsvrDisable()                (sysfl &=(~(0x1U<<22)))
#define IsScrnsvrEnabled()              (sysfl &   (0x1U<<22))
#define ScrnsvrInitSet()                (sysfl |=  (0x1U<<23))
#define ScrnsvrInitReset()              (sysfl &=(~(0x1U<<23)))
#define IsScrnsvrInitActiv()            (sysfl &   (0x1U<<23))
#define ScrnsvrSet()                    (sysfl |=  (0x1U<<24)) 
#define ScrnsvrReset()                  (sysfl &=(~(0x1U<<24)))
#define IsScrnsvrActiv()                (sysfl &   (0x1U<<24))
#define ScreenInitSet()                 (sysfl |=  (0x1U<<25))
#define ScreenInitReset()               (sysfl &=(~(0x1U<<25)))
#define IsScreenInitActiv()             (sysfl &   (0x1U<<25))
#define BtnOkPresed()                   (sysfl |=  (0x1U<<26)) 
#define BtnOkRelease()                  (sysfl &=(~(0x1U<<26)))
#define IsBtnOkPressed()                (sysfl &   (0x1U<<26))
#define ButtonDndSet()                  (sysfl |=  (0x1U<<27)) 
#define ButtonDndReset()                (sysfl &=(~(0x1U<<27)))
#define IsButtonDndActiv()              (sysfl &   (0x1U<<27))
#define ButtonSosSet()                  (sysfl |=  (0x1U<<28)) 
#define ButtonSosReset()                (sysfl &=(~(0x1U<<28)))
#define IsButtonSosActiv()              (sysfl &   (0x1U<<28))
#define ButtonCallSet()                 (sysfl |=  (0x1U<<29)) 
#define ButtonCallReset()               (sysfl &=(~(0x1U<<29)))
#define IsButtonCallActiv()             (sysfl &   (0x1U<<29))
#define StatUpdSet()                    (sysfl |=  (0x1U<<30))
#define StatUpdReset()				    (sysfl &=(~(0x1U<<30)))
#define IsStatUpdActiv()                (sysfl &   (0x1U<<30))
#define SYS_StartupSet()                (sysfl |=  (0x1U<<31))
#define SYS_StartupReset()              (sysfl &=(~(0x1U<<31)))	
#define IsSYS_StartupActiv()            (sysfl &   (0x1U<<31))
/***********************************************************************
**	 	F L A G S 		2      R E G I S T E R 
***********************************************************************/
#define DISP_ImgUpdSet()                (sysfl1 |=  (0x1U<<0))
#define DISP_imgUpdReset()              (sysfl1 &=(~(0x1U<<0)))
#define IsDISP_ImgUpdActiv()            (sysfl1 &   (0x1U<<0))
#define DISP_FwUpdSet()                 (sysfl1 |=  (0x1U<<1))
#define DISP_FwUpdReset()               (sysfl1 &=(~(0x1U<<1)))
#define IsDISP_FwUpdActiv()             (sysfl1 &   (0x1U<<1))
#define DISP_UpdateSet()                (sysfl1 |=  (0x1U<<2))
#define DISP_UpdateReset()              (sysfl1 &=(~(0x1U<<2)))
#define IsDISP_UpdateActiv()            (sysfl1 &   (0x1U<<2))
#define DISP_BldrUpdSet()               (sysfl1 |=  (0x1U<<3))
#define DISP_BldrUpdReset()             (sysfl1 &=(~(0x1U<<3)))
#define IsDISP_BldrUpdSetActiv()        (sysfl1 &   (0x1U<<3))
#define DISP_BldrUpdFailSet()           (sysfl1 |=  (0x1U<<4))
#define DISP_BldrUpdFailReset()         (sysfl1 &=(~(0x1U<<4)))
#define IsDISP_BldrUpdFailActiv()       (sysfl1 &   (0x1U<<4))
#define DISP_PreviewImage()             (sysfl1 |=  (0x1U<<5))
#define DISP_PreviewImgDel()            (sysfl1 &=(~(0x1U<<5)))
#define IsDISP_PreviewImgActiv()        (sysfl1 &   (0x1U<<5))
#define DISP_RoomNumImgSet()            (sysfl1 |=  (0x1U<<6))
#define DISP_RoomNumImgReset()          (sysfl1 &=(~(0x1U<<6)))
#define IsDISP_RoomNumImgActiv()        (sysfl1 &   (0x1U<<6))
#define DISP_DndImg()                   (sysfl1 |=  (0x1U<<7))
#define DISP_DndImgDelete()             (sysfl1 &=(~(0x1U<<7)))
#define IsDISP_DndImgActiv()            (sysfl1 &   (0x1U<<7))
#define DISP_SosAlarmImage()            (sysfl1 |=  (0x1U<<8))
#define DISP_SosAlarmImgDel()           (sysfl1 &=(~(0x1U<<8)))
#define IsDISP_SosAlarmImgActiv()       (sysfl1 &   (0x1U<<8))
#define DISP_CleanUpImage()             (sysfl1 |=  (0x1U<<9))
#define DISP_CleanUpImgDel()            (sysfl1 &=(~(0x1U<<9)))
#define IsDISP_CleanUpImgActiv()        (sysfl1 &   (0x1U<<9))
#define DISP_GeneralCleanUpImg()        (sysfl1 |=  (0x1U<<10))
#define DISP_GenClnImgDelete()          (sysfl1 &=(~(0x1U<<10)))
#define IsDISP_GenCleanImgActiv()       (sysfl1 &   (0x1U<<10))
#define DISP_CardValidImage()           (sysfl1 |=  (0x1U<<11))
#define DISP_CardValidImgDel()          (sysfl1 &=(~(0x1U<<11)))
#define IsDISP_CardValidImgActiv()      (sysfl1 &   (0x1U<<11))
#define DISP_CardInvalidImage()         (sysfl1 |=  (0x1U<<12))
#define DISP_CardInvalidImgDel()        (sysfl1 &=(~(0x1U<<12)))
#define IsDISP_CardInvalidImgActiv()    (sysfl1 &   (0x1U<<12))
#define DISP_WrongRoomImage()           (sysfl1 |=  (0x1U<<13))
#define DISP_WrongRoomImgDel()          (sysfl1 &=(~(0x1U<<13)))
#define IsDISP_WrongRoomImgActiv()      (sysfl1 &   (0x1U<<13))
#define DISP_TimeExpiredImage()         (sysfl1 |=  (0x1U<<14))
#define DISP_TimeExpiredImgDel()        (sysfl1 &=(~(0x1U<<14)))
#define IsDISP_TimeExpiredImgActiv()    (sysfl1 &   (0x1U<<14))
#define DISP_OutOfSrvcImgSet()          (sysfl1 |=  (0x1U<<15))
#define DISP_OutOfSrvcImgReset()        (sysfl1 &=(~(0x1U<<15)))
#define IsDISP_OutOfSrvcImgActiv()      (sysfl1 &   (0x1U<<15))
#define DISP_DoorBellOpen()             (sysfl1 |=  (0x1U<<16))
#define DISP_DoorBellOpenDel()          (sysfl1 &=(~(0x1U<<16)))
#define IsDISP_DoorBellOpenActiv()      (sysfl1 &   (0x1U<<16))
#define DISP_FireExitImage()            (sysfl1 |=  (0x1U<<17))
#define DISP_FireExitImgDel()           (sysfl1 &=(~(0x1U<<17)))
#define IsDISP_FireExitImgActiv()       (sysfl1 &   (0x1U<<17))
#define DISP_FireAlarmImage()           (sysfl1 |=  (0x1U<<18))
#define DISP_FireAlarmImgDel()          (sysfl1 &=(~(0x1U<<18)))
#define IsDISP_FireAlarmImgActiv()      (sysfl1 &   (0x1U<<18))
#define DISP_BeddRepImg()               (sysfl1 |=  (0x1U<<19))
#define DISP_BeddRepImgDelete()         (sysfl1 &=(~(0x1U<<19)))
#define IsDISP_BeddRepImgActiv()        (sysfl1 &   (0x1U<<19))
#define DISP_UpdProgMsgSet()            (sysfl1 |=  (0x1U<<20))
#define DISP_UpdProgMsgDel()            (sysfl1 &=(~(0x1U<<20)))
#define IsDISP_UpdProgMsgActiv()        (sysfl1 &   (0x1U<<20))
#define DISP_FwrUpdd()                  (sysfl1 |=  (0x1U<<21))
#define DISP_FwrUpddDelete()            (sysfl1 &=(~(0x1U<<21)))
#define IsDISP_FwrUpddActiv()           (sysfl1 &   (0x1U<<21))
#define DISP_FwrUpdFail()               (sysfl1 |=  (0x1U<<22))
#define DISP_FwrUpdFailDelete()         (sysfl1 &=(~(0x1U<<22)))
#define IsDISP_FwrUpdFailActiv()        (sysfl1 &   (0x1U<<22))
#define DISP_CallMaidImg()              (sysfl1 |=  (0x1U<<23))
#define DISP_CallMaidImgDelete()        (sysfl1 &=(~(0x1U<<23)))
#define IsDISP_CallMaidImgActiv()       (sysfl1 &   (0x1U<<23))
#define DISP_FwUpdFailSet()             (sysfl1 |=  (0x1U<<24))
#define DISP_FwUpdFailReset()           (sysfl1 &=(~(0x1U<<24)))
#define IsDISP_FwUpdFailActiv()         (sysfl1 &   (0x1U<<24))
#define DISP_DoorBellSet()              (sysfl1 |=  (0x1U<<25))
#define DISP_DoorBellReset()            (sysfl1 &=(~(0x1U<<25)))
#define IsDISP_DoorBellActiv()          (sysfl1 &   (0x1U<<25))
#define DISP_CleaningSet()              (sysfl1 |=  (0x1U<<26))
#define DISP_CleaningReset()            (sysfl1 &=(~(0x1U<<26)))
#define IsDISP_CleaningActiv()          (sysfl1 &   (0x1U<<26))
#define DISP_KeypadSet()                (sysfl1 |=  (0x1U<<27))
#define DISP_KeypadReset()              (sysfl1 &=(~(0x1U<<27)))
#define IsDISP_KeypadActiv()            (sysfl1 &   (0x1U<<27))
#define DISP_UnlockSet()                (sysfl1 |=  (0x1U<<28))
#define DISP_UnlockReset()              (sysfl1 &=(~(0x1U<<28)))
#define IsDISP_UnlockActiv()            (sysfl1 &   (0x1U<<28))
#define DISP_LanguageSet()              (sysfl1 |=  (0x1U<<29))
#define DISP_LanguageReset()            (sysfl1 &=(~(0x1U<<29)))
#define IsDISP_LanguageActiv()          (sysfl1 &   (0x1U<<29))
#define DISP_SettingsInitSet()          (sysfl1 |=  (0x1U<<30))	
#define DISP_SettingsInitReset()        (sysfl1 &=(~(0x1U<<30)))
#define IsDISP_SettingsInitActiv()      (sysfl1 &   (0x1U<<30))
#define DISP_RefreshSet()               (sysfl1 |=  (0x1U<<31))
#define DISP_RefreshReset()             (sysfl1 &=(~(0x1U<<31)))
#define IsDISP_RefreshActiv()           (sysfl1 &   (0x1U<<31))
/***********************************************************************
**	 	F L A G S 		3      R E G I S T E R 
***********************************************************************/
#define DISP_UserInfoEnable()           (sysfl2 |=  (0x1U<<0))
#define DISP_UserInfoDisable()          (sysfl2 &=(~(0x1U<<0)))
#define IsDISP_UserInfoEnabled()        (sysfl2 &   (0x1U<<0))
#define ScrnsvrClkSet()                 (sysfl2 |=  (0x1U<<1)) // flag for screensaver digital clock selection
#define ScrnsvrClkReset()               (sysfl2 &=(~(0x1U<<1)))
#define IsScrnsvrClkActiv()             (sysfl2 &   (0x1U<<1))
#define ScrnsvrSemiClkSet()             (sysfl2 |=  (0x1U<<2)) // flag for screensaver small logo sze digital clock selection
#define ScrnsvrSemiClkReset()           (sysfl2 &=(~(0x1U<<2)))
#define IsScrnsvrSemiClkActiv()         (sysfl2 &   (0x1U<<2))
#define DoNotDisturbOn()                (sysfl2 |=  (0x1U<<3))
#define DoNotDisturbOff()				(sysfl2 &=(~(0x1U<<3)))
#define IsDonNotDisturbActiv()			(sysfl2 &   (0x1U<<3))
#define RightButtonSet()			    (sysfl2 |=  (0x1U<<4))
#define RightButtonReset()		        (sysfl2 &=(~(0x1U<<4)))
#define IsRightButtonActiv()		    (sysfl2 &   (0x1U<<4))
#define LeftButtonSet()			        (sysfl2 |=  (0x1U<<5))
#define LeftButtonReset()		        (sysfl2 &=(~(0x1U<<5)))
#define IsLeftButtonActiv()		        (sysfl2 &   (0x1U<<5))
#define CallMaidSet()				    (sysfl2 |=  (0x1U<<6))
#define CallMaidReset()				    (sysfl2 &=(~(0x1U<<6)))
#define IsCallMaidActiv()			    (sysfl2 &   (0x1U<<6))
#define PwrExpTimeSet()                 (sysfl2 |=  (0x1U<<7))
#define PwrExpTimeReset()               (sysfl2 &=(~(0x1U<<7)))
#define IsPwrExpTimeActiv()             (sysfl2 &   (0x1U<<7))
#define RtcTimeValidSet()               (sysfl2 |=  (0x1U<<8))
#define RtcTimeValidReset()             (sysfl2 &=(~(0x1U<<8)))
#define IsRtcTimeValid()                (sysfl2 &   (0x1U<<8))
#define RoomCleaningSet()               (sysfl2 |=  (0x1U<<9))  // disable touch sensors due room cleaning
#define RoomCleaningReset()             (sysfl2 &=(~(0x1U<<9)))
#define IsRoomCleaningActiv()           (sysfl2 &   (0x1U<<9))
#define CardDataRdySet()                (sysfl2 |=  (0x1U<<10))  // new card data ready
#define CardDataRdyReset()              (sysfl2 &=(~(0x1U<<10))) // clear flag after data processing to enable nexr read
#define IsCardDataRdyActiv()            (sysfl2 &   (0x1U<<10))  // check is new card data ready in bufer 
#define HandmaidReentranceEnable()      (sysfl2 |=  (0x1U<<11))  // enable to handmaid to open room without clearing services
#define HandmaidReentranceDisable()     (sysfl2 &=(~(0x1U<<11)))
#define IsHandmaidReentranceActiv()     (sysfl2 &   (0x1U<<11))
#define ExtendDoorlockTimeSet()         (sysfl2 |=  (0x1U<<12))  // doorlock event from extenal source 
#define ExtendDoorlockTimeReset()       (sysfl2 &=(~(0x1U<<12)))
#define IsExtendDoorlockTimeActiv()     (sysfl2 &   (0x1U<<12)) 
#define NtcErrorSet()                   (sysfl2 |=  (0x1U<<13))
#define NtcErrorReset()                 (sysfl2 &=(~(0x1U<<13)))
#define IsNtcErrorActiv()               (sysfl2 &   (0x1U<<13))
#define RoomCtrlConfig()                (sysfl2 |=  (0x1U<<14))
#define RoomThstConfig()                (sysfl2 &=(~(0x1U<<14)))
#define IsRoomCtrlConfig()              (sysfl2 &   (0x1U<<14))
#define IsRoomThstConfig()              (!(sysfl2 & (0x1U<<14)))
#define TempSenLuxRTSet()               (sysfl2 |=  (0x1U<<15))
#define TempSenLuxRTReset()             (sysfl2 &=(~(0x1U<<15)))
#define IsTempLuxRTActive()             (sysfl2 &   (0x1U<<15))
#define TempSenDS18Set()                (sysfl2 |=  (0x1U<<16))
#define TempSenDS18Reset()              (sysfl2 &=(~(0x1U<<16)))
#define IsTempSenDS18Active()           (sysfl2 &   (0x1U<<16))
#define TempSenNTCSet()                 (sysfl2 |=  (0x1U<<17))
#define TempSenNTCReset()               (sysfl2 &=(~(0x1U<<17)))
#define IsTempSenNTCActive()            (sysfl2 &   (0x1U<<17))

#define ThermostatOn()                  (sysfl2 |=  (0x1U<<18))
#define ThermostatOff()                 (sysfl2 &=(~(0x1U<<18)))
#define IsThermostatActiv()             (sysfl2 &   (0x1U<<18))

#define TempRegOn()                     (sysfl2 |=  (0x1U<<19))    // config On: controll loop is executed periodicaly
#define TempRegOff()                    (sysfl2 &=(~(0x1U<<19)))   // config Off:controll loop stopped, 
#define IsTempRegActiv()                (sysfl2 &   (0x1U<<19))

#define TempRegHeating()                (sysfl2 |=  (0x1U<<20))    // config Heating: output activ for setpoint value 
#define IsTempRegHeating()              (sysfl2 &   (0x1U<<20))    // abbove measured value
#define IsTempRegCooling()              (!(sysfl2 & (0x1U<<20)))
#define TempRegCooling()                (sysfl2 &=(~(0x1U<<20)))   // config Cooling: opposite from heating

#define TempRegEnable()                 (sysfl2 |=  (0x1U<<21))    // conditional flag Enable: controll loop set output state
#define TempRegDisable()                (sysfl2 &=(~(0x1U<<21)))   // conditional flag Disable:output is forced to inactiv state, controll loop cannot change outpu
#define IsTempRegEnabled()              (sysfl2 &   (0x1U<<21))

#define TempRegOutputOn()               (sysfl2 |=  (0x1U<<22))    // status On: output demand for actuator to inject energy in to system
#define TempRegOutputOff()              (sysfl2 &=(~(0x1U<<22)))   // status Off:stop demanding energy for controlled system, setpoint is reached
#define IsTempRegOutputActiv()          (sysfl2 &   (0x1U<<22))

#define HVACOutputOn()                  (sysfl2 |=  (0x1U<<23))    
#define HVACOutputOff()                 (sysfl2 &=(~(0x1U<<23)))
#define IsHVACOutputActiv()             (sysfl2 &   (0x1U<<23))

#define HVAC_ContactorOn()			    (sysfl2 |=  (0x1U<<24))
#define HVAC_ContactorOff()			    (sysfl2 &=(~(0x1U<<24)))
#define IsHVAC_ContactorActiv()		    (sysfl2 &   (0x1U<<24))

#define ExtHVAC_ContactorOn()           (sysfl2 |=  (0x1U<<25))
#define ExtHVAC_ContactorOff()          (sysfl2 &=(~(0x1U<<25)))
#define IsExtHVAC_ContactorActiv()      (sysfl2 &   (0x1U<<25))

#define PowerContactorOn()              (sysfl2 |=  (0x1U<<26)) /* pin 30 "IZLAZ ODLAGACA" prema Edinovoj skici */
#define PowerContactorOff()             (sysfl2 &=(~(0x1U<<26)))
#define IsPowerContactorActiv()			(sysfl2 &   (0x1U<<26))

#define ExtPowerContactorOn()           (sysfl2 |=  (0x1U<<27))
#define ExtPowerContactorOff()          (sysfl2 &=(~(0x1U<<27)))
#define IsExtPowerContactorActiv()      (sysfl2 &   (0x1U<<27))
/***********************************************************************
**	 	F L A G S 		3      R E G I S T E R 
***********************************************************************/
#define DoorLockOn()                    (sysfl3 |=  (0x1U<<0))
#define DoorLockOff()                   (sysfl3 &=(~(0x1U<<0)))
#define IsDoorLockActiv()               (sysfl3 &   (0x1U<<0))

#define BuzzerOn()                      (sysfl3 |=  (0x1U<<1))
#define BuzzerOff()                     (sysfl3 &=(~(0x1U<<1)))
#define IsBuzzerActiv()					(sysfl3 &   (0x1U<<1))

#define WinDoorSwOn()                   (sysfl3 |=  (0x1U<<2))
#define WinDoorSwOff()                  (sysfl3 &=(~(0x1U<<2)))
#define IsWinDoorSwActiv()              (sysfl3 &   (0x1U<<2))
#define WinDoorSwEnable()               (sysfl3 |=  (0x1U<<3)) 
#define WinDoorSwDisable()              (sysfl3 &=(~(0x1U<<3)))
#define IsWinDoorSwEnabled()            (sysfl3 &   (0x1U<<3))  

#define ExtWinDoorSwOn()                (sysfl3 |=  (0x1U<<4))
#define ExtWinDoorSwOff()               (sysfl3 &=(~(0x1U<<4)))
#define IsExtWinDoorSwActiv()           (sysfl3 &   (0x1U<<4))
#define ExtWinDoorSwEnable()            (sysfl3 |=  (0x1U<<5)) 
#define ExtWinDoorSwDisable()           (sysfl3 &=(~(0x1U<<5)))
#define IsExtWinDoorSwEnabled()         (sysfl3 &   (0x1U<<5)) 

#define CardStackerOn()                 (sysfl3 |=  (0x1U<<6)) 
#define CardStackerOff()                (sysfl3 &=(~(0x1U<<6)))
#define IsCardStackerActiv()            (sysfl3 &   (0x1U<<6)) 
#define CardStackerEnable()             (sysfl3 |=  (0x1U<<7)) 
#define CardStackerDisable()            (sysfl3 &=(~(0x1U<<7)))   
#define IsCardStackerEnabled()          (sysfl3 &   (0x1U<<7)) 

#define ExtCardStackerOn()              (sysfl3 |=  (0x1U<<8))
#define ExtCardStackerOff()             (sysfl3 &=(~(0x1U<<8)))
#define IsExtCardStackerActiv()         (sysfl3 &   (0x1U<<8))
#define ExtCardStackerEnable()          (sysfl3 |=  (0x1U<<9))
#define ExtCardStackerDisable()         (sysfl3 &=(~(0x1U<<9)))
#define IsExtCardStackerEnabled()       (sysfl3 &   (0x1U<<9))

#define OWCardStackerOn()               (sysfl3 |=  (0x1U<<10)) 
#define OWCardStackerOff()              (sysfl3 &=(~(0x1U<<10)))
#define IsOWCardStackerActiv()          (sysfl3 &   (0x1U<<10)) 
#define OWCardStackerEnable()           (sysfl3 |=  (0x1U<<11))
#define OWCardStackerDisable()          (sysfl3 &=(~(0x1U<<11)))
#define IsOWCardStackerEnabled()        (sysfl3 &   (0x1U<<11)) 

#define EntryDoorSwOn()		            (sysfl3 |=  (0x1U<<12))
#define EntryDoorSwOff()                (sysfl3 &=(~(0x1U<<12)))
#define IsEntryDoorSwActiv()            (sysfl3 &   (0x1U<<12))
#define EntryDoorSwEnable()             (sysfl3 |=  (0x1U<<13)) 
#define IsEntryDoorSwEnabled()          (sysfl3 &   (0x1U<<13))

#define DoorBellOn()                    (sysfl3 |=  (0x1U<<14))
#define DoorBellOff()                   (sysfl3 &=(~(0x1U<<14)))
#define IsDoorBellActiv()               (sysfl3 &   (0x1U<<14))

#define DoorlockRemoteOpenSet()         (sysfl3 |=  (0x1U<<15))   
#define DoorlockRemoteOpenReset()       (sysfl3 &=(~(0x1U<<15)))
#define IsDoorlockRemoteOpenActiv()     (sysfl3 &   (0x1U<<15))

/* Exported functions  -------------------------------------------------------*/
#endif
/************************ (C) COPYRIGHT JUBERA D.O.O Sarajevo ************************/
